### ISSUE TITLE
请问：Docker跑不起来，报错

### ISSUE THREAD

**Issue by BladeWong** [pluosi/app-host#39]
docker logs显示报错如下：
[ ok ] Starting nginx: nginx.
Puma starting in single mode...
* Version 3.9.1 (ruby 2.5.0-p0), codename: Private Caller
* Min threads: 1, max threads: 1
* Environment: production
/app/config/initializers/rack.rb:3: warning: already initialized constant Rack::Multipart::Parser::BUFSIZE
/usr/local/bundle/gems/rack-2.0.3/lib/rack/multipart/parser.rb:8: warning: previous definition of BUFSIZE was here
* Listening on tcp://0.0.0.0:3000
Traceback (most recent call last):
	9: from /usr/local/bundle/bin/puma:29:in `<main>'
	8: from /usr/local/bundle/bin/puma:29:in `load'
	7: from /usr/local/bundle/gems/puma-3.9.1/bin/puma:10:in `<top (required)>'
	6: from /usr/local/bundle/gems/puma-3.9.1/lib/puma/cli.rb:77:in `run'
	5: from /usr/local/bundle/gems/puma-3.9.1/lib/puma/launcher.rb:174:in `run'
	4: from /usr/local/bundle/gems/puma-3.9.1/lib/puma/single.rb:92:in `run'
	3: from /usr/local/bundle/gems/puma-3.9.1/lib/puma/launcher.rb:103:in `write_state'
	2: from /usr/local/bundle/gems/puma-3.9.1/lib/puma/launcher.rb:130:in `write_pid'
	1: from /usr/local/bundle/gems/puma-3.9.1/lib/puma/launcher.rb:130:in `open'
/usr/local/bundle/gems/puma-3.9.1/lib/puma/launcher.rb:130:in `initialize': No such file or directory @ rb_sysopen - tmp/pids/puma.pid (Errno::ENOENT)

**Comment by iBcker** [comment]
这个报错很奇怪。。。我建议删了再试一次

**Comment by CNGTZ** [comment]
请问你这个问题解决了吗？我的docker运行后也启动不起来，查看log显示的错误和你差不多呢

**Comment by CNGTZ** [comment]
ubuntu还是centos？我的ubuntu没问题，centos有这个问题

**Comment by hack2012** [comment]
> docker logs显示报错如下：
> [ ok ] Starting nginx: nginx.
> Puma starting in single mode...
> 
> * Version 3.9.1 (ruby 2.5.0-p0), codename: Private Caller
> * Min threads: 1, max threads: 1
> * Environment: production
>   /app/config/initializers/rack.rb:3: warning: already initialized constant Rack::Multipart::Parser::BUFSIZE
>   /usr/local/bundle/gems/rack-2.0.3/lib/rack/multipart/parser.rb:8: warning: previous definition of BUFSIZE was here
> * Listening on tcp://0.0.0.0:3000
>   Traceback (most recent call last):
>   9: from /usr/local/bundle/bin/puma:29:in `<main>' 8: from /usr/local/bundle/bin/puma:29:in `load'
>   7: from /usr/local/bundle/gems/puma-3.9.1/bin/puma:10:in `<top (required)>' 6: from /usr/local/bundle/gems/puma-3.9.1/lib/puma/cli.rb:77:in `run'
>   5: from /usr/local/bundle/gems/puma-3.9.1/lib/puma/launcher.rb:174:in `run' 4: from /usr/local/bundle/gems/puma-3.9.1/lib/puma/single.rb:92:in `run'
>   3: from /usr/local/bundle/gems/puma-3.9.1/lib/puma/launcher.rb:103:in `write_state' 2: from /usr/local/bundle/gems/puma-3.9.1/lib/puma/launcher.rb:130:in `write_pid'
>   1: from /usr/local/bundle/gems/puma-3.9.1/lib/puma/launcher.rb:130:in `open' /usr/local/bundle/gems/puma-3.9.1/lib/puma/launcher.rb:130:in `initialize': No such file or directory @ rb_sysopen - tmp/pids/puma.pid (Errno::ENOENT)

经测试是因为默认的nginx.conf中的一个配置导致了请求会由http post 到https 所以浏览器会拒绝。
解决办法：将 docker/nginx.conf 中 proxy_set_header  X-Forwarded-Ssl on; 这个配置前面加个# 号即可解决。
