### ISSUE TITLE
docker 启动成功，但是页面不能访问

### ISSUE THREAD

**Issue by tanpengsccd** [pluosi/app-host#60]
docker 启动成功 已经用caddy 配置服务 将 路径 / proxy到 localhost:3000 并开启tls
```
docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED              STATUS              PORTS                      NAMES
a963040aa929        local_pluosi/app_host:0.1.1   "/bin/sh -c '/bin/ba…"   About a minute ago   Up About a minute   0.0.0.0:3000->8686/tcp     app_host
027ad8e33050        docker_server                 "npm start"              23 hours ago         Up 16 hours         0.0.0.0:9898->9898/tcp     docker_server_1
90e93d03a76b        mongo                         "docker-entrypoint.s…"   23 hours ago         Up 23 hours         0.0.0.0:27017->27017/tcp   mongo
```
但是访问域名页面 会重定向到 localhost:3000，失败
可看到日志    
cat shared/log/puma.error.log
```
=== puma startup: 2019-06-18 06:58:22 +0000 ===
➜  app-host git:(master) cat shared/log/production.log
I, [2019-06-18T06:58:30.430815 #63]  INFO -- : [8a130b62-9f2f-4bb7-9ba2-d0dd63c56bcc] Started GET "/" for 101.207.125.98 at 2019-06-18 06:58:30 +0000
I, [2019-06-18T06:58:30.433620 #63]  INFO -- : [8a130b62-9f2f-4bb7-9ba2-d0dd63c56bcc] Processing by AppsController#index as HTML
D, [2019-06-18T06:58:30.466307 #63] DEBUG -- : [8a130b62-9f2f-4bb7-9ba2-d0dd63c56bcc]   User Exists (0.4ms)  SELECT  1 AS one FROM "users" WHERE "users"."deleted_at" IS NULL AND "users"."role" = ? LIMIT ?  [["role", "admin"], ["LIMIT", 1]]
I, [2019-06-18T06:58:30.467089 #63]  INFO -- : [8a130b62-9f2f-4bb7-9ba2-d0dd63c56bcc] Redirected to https://localhost:3000/users/new
I, [2019-06-18T06:58:30.467415 #63]  INFO -- : [8a130b62-9f2f-4bb7-9ba2-d0dd63c56bcc] Completed 302 Found in 34ms (ActiveRecord: 3.4ms)
```

**Comment by tanpengsccd** [comment]
然后尝试修改配置文件 emacs shared/config/settings.local.yml
```
PROTOCOL: "http://"
HOST: "localhost:3000"

# SECRET_KEY_BASE: "可以运行rake secret,docker用户会自动生成，可忽略"
#-- secret_key_base create by laucher --
SECRET_KEY_BASE: 326e04b7de92767b93c7bcaba0f050b09b96e146b6afc13a150716310de8a3fa94449ab8588fe8231884414b5e8bd4d818e72a38c430dd9b792401ba85774de1
```
重启

```
./docker/launcher restart
+ docker stop -t 10 app_host
app_host
[2019-06-18 03:11:14] starting up existing container
+ docker start app_host
app_host
```
但是访问域名问题依旧

**Comment by tanpengsccd** [comment]
然后 再尝试修改 config/settings.local.yml 

```
PROTOCOL: "https://"
HOST: "zhjk.h6.work"

# SECRET_KEY_BASE: "可以运行rake secret,docker用户会自动生成，可忽略"
#-- secret_key_base create by laucher --
SECRET_KEY_BASE: 326e04b7de92767b93c7bcaba0f050b09b96e146b6afc13a150716310de8a3fa94449ab8588fe8231884414b5e8bd4d818e72a38c430dd9b792401ba85774de1
```



重启docker 还是跳转localhost

**Comment by iBcker** [comment]
因为 docker 构建是会吧配置文件构建到镜像里的，所以你得先改了配置再构建，如果已经构建了，得重新构建才能让修改生效，重启不会动配置。


可以试试先 destroy 再 bootstrap。

**Comment by tanpengsccd** [comment]
```
./docker/launcher destroy
./docker/launcher bootstrap -v
./docker/launcher start
```
访问还是跳转localhost:3000

其中./docker/launcher bootstrap -v 时有几段红字 我贴出来了

```
Step 13/16 : RUN rake db:migrate
 ---> Running in dfbad4757306
/app/config/initializers/rack.rb:3: warning: already initialized constant Rack::Multipart::Parser::BUFSIZE
/usr/local/bundle/gems/rack-2.0.7/lib/rack/multipart/parser.rb:8: warning: previous definition of BUFSIZE was here
Removing intermediate container dfbad4757306
 ---> 4d3ffde49401
Step 14/16 : RUN rake assets:precompile
 ---> Running in 8bbe0e0d2cba
/app/config/initializers/rack.rb:3: warning: already initialized constant Rack::Multipart::Parser::BUFSIZE
/usr/local/bundle/gems/rack-2.0.7/lib/rack/multipart/parser.rb:8: warning: previous definition of BUFSIZE was here
Yarn executable was not detected in the system.
Download Yarn at https://yarnpkg.com/en/docs/install
I, [2019-06-18T08:06:33.601293 #6]  INFO -- : Writing /app/public/assets/application-7898dadf2c6065f94969b7f3a54fbd815b8de9f2393fb2a58c86ecc6430f7fc0.js
I, [2019-06-18T08:06:33.603199 #6]  INFO -- : Writing /app/public/assets/application-7898dadf2c6065f94969b7f3a54fbd815b8de9f2393fb2a58c86ecc6430f7fc0.js.gz
I, [2019-06-18T08:06:47.562142 #6]  INFO -- : Writing /app/public/assets/application-d4f9a943246d44dc4d0c80821a78948c21a9bfdb2a10d3ad591eecd513d8f746.css
I, [2019-06-18T08:06:47.562787 #6]  INFO -- : Writing /app/public/assets/application-d4f9a943246d44dc4d0c80821a78948c21a9bfdb2a10d3ad591eecd513d8f746.css.gz
I, [2019-06-18T08:06:47.565404 #6]  INFO -- : Writing /app/public/assets/bootstrap/glyphicons-halflings-regular-13634da87d9e23f8c3ed9108ce1724d183a39ad072e73e1b3d8cbf646d2d0407.eot
I, [2019-06-18T08:06:47.566945 #6]  INFO -- : Writing /app/public/assets/bootstrap/glyphicons-halflings-regular-13634da87d9e23f8c3ed9108ce1724d183a39ad072e73e1b3d8cbf646d2d0407.eot.gz
I, [2019-06-18T08:06:47.567963 #6]  INFO -- : Writing /app/public/assets/bootstrap/glyphicons-halflings-regular-fe185d11a49676890d47bb783312a0cda5a44c4039214094e7957b4c040ef11c.woff2
I, [2019-06-18T08:06:47.571327 #6]  INFO -- : Writing /app/public/assets/bootstrap/glyphicons-halflings-regular-a26394f7ede100ca118eff2eda08596275a9839b959c226e15439557a5a80742.woff
I, [2019-06-18T08:06:47.572929 #6]  INFO -- : Writing /app/public/assets/bootstrap/glyphicons-halflings-regular-e395044093757d82afcb138957d06a1ea9361bdcf0b442d06a18a8051af57456.ttf
I, [2019-06-18T08:06:47.575450 #6]  INFO -- : Writing /app/public/assets/bootstrap/glyphicons-halflings-regular-e395044093757d82afcb138957d06a1ea9361bdcf0b442d06a18a8051af57456.ttf.gz
I, [2019-06-18T08:06:47.576762 #6]  INFO -- : Writing /app/public/assets/bootstrap/glyphicons-halflings-regular-42f60659d265c1a3c30f9fa42abcbb56bd4a53af4d83d316d6dd7a36903c43e5.svg
I, [2019-06-18T08:06:47.578998 #6]  INFO -- : Writing /app/public/assets/bootstrap/glyphicons-halflings-regular-42f60659d265c1a3c30f9fa42abcbb56bd4a53af4d83d316d6dd7a36903c43e5.svg.gz
I, [2019-06-18T08:06:47.689064 #6]  INFO -- : Writing /app/public/assets/normalize-rails/normalize-d614e0bcbbd9f3542ef8b53f8a33aac3a58291c5f990c933a30aaa505c816df1.css
I, [2019-06-18T08:06:47.689528 #6]  INFO -- : Writing /app/public/assets/normalize-rails/normalize-d614e0bcbbd9f3542ef8b53f8a33aac3a58291c5f990c933a30aaa505c816df1.css.gz
Removing intermediate container 8bbe0e0d2cba
```

**Comment by tanpengsccd** [comment]
这个或不是错误吧。
![image](https://user-images.githubusercontent.com/13959880/59665534-ac8d7200-91e5-11e9-8873-e3d212f0078c.png)

**Comment by tanpengsccd** [comment]
可能是nginx 配置问题 https://github.com/pluosi/app-host/issues/26
我用的caddy 修改后不使用docker方式，rails s 可以跑起来了
cat /etc/caddy/Caddyfile
```
www.mydomain.com {
	     proxy / localhost:3000 {
	     	   transparent
	     }

}#
```

**Comment by tanpengsccd** [comment]
但是用 还是出现了另个问题
cat shared/log/puma.error.log
```
2019-06-18 09:34:12 +0000: Rack app error handling request { GET / }
#<RuntimeError: Missing `secret_key_base` for 'production' environment, set this value in `config/secrets.yml`>
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application.rb:510:in `validate_secret_key_config!'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application.rb:247:in `env_config'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/engine.rb:692:in `build_request'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application.rb:518:in `build_request'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/engine.rb:521:in `call'
/usr/local/bundle/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
/usr/local/bundle/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
/usr/local/bundle/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
/usr/local/bundle/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
/usr/local/bundle/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

**Comment by tanpengsccd** [comment]
把 config/settings.local.yml的
`SECRET_KEY_BASE: xxxxxxxxxxx` 这行信息
再执行
```
./docker/launcher destroy
./docker/launcher bootstrap -v
./docker/launcher start
```
done ！ 终于成功

**Comment by tanpengsccd** [comment]
建议用上面caddy 服务配置 非常简单

**Comment by iBcker** [comment]
rails s  建议跑生产模式，不然性能比较低。 RAILS_ENV=production  rails s

**Comment by tanpengsccd** [comment]
Ok! thanks,我用的docker，好维护些
